import localFont from "next/font/local";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/authOptions";
import AuthProvider from "./components/AuthProvider";
import "./globals.css"; // Import global styles

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the app
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout Component
export default async function RootLayout({ children }) {
  // Fetch the session on the server side
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Provide session context to all components */}
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
